spring:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    encoding:
      charset: utf-8

logging:
  level:
    org.hibernate.sql: debug