spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    encoding:
      charset: utf-8

logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret: QmFja2VuZERldmVsb3BlclJ1YnlSYWJiaXRCYWNrZW5kRGV2ZWxvcGVyUnVieVJhYmJpdEJhY2tlbmREZXZlbG9wZXJSdWJ5UmFiYml0
  expireTime: 300000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    use-root-path: true